name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install, lint, and test
        run: |
          npm ci
          npm run bootstrap
          npm run lint
          npm run test

  continuous-delivery:
    runs-on: ubuntu-latest
    needs: continuous-integration

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install, lint, and test
        run: |
          npm ci
          npm run bootstrap
          npm run build

      - name: Continuous Deployment to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: packages/storybook/dist
